import './globals.css';
import type { Metadata } from 'next';
import type { ChildrenType } from '@/models';
import { Providers } from "@/providers";

// Metadata para la pagina principal de la aplicación.
export const metadata: Metadata = {
  title: 'G-Blog',
  description: 'Generated by create next app',
};

/**
 * Function to create the main component/layout of the application.
 * 
 * @param { ChildrenType } param0 - Default model of the properties of a component in React.
 * 
 * @returns { JSX.Element } Root component.
 */
// Función para crear el componente/layout principal de la aplicación.
export default function RootLayout(
  { children }: ChildrenType
): JSX.Element {
  return (
    <html lang="en">
      <body className='
        w-full h-full min-h-screen bg-cover bg-gradient-to-bl 
        dark:from-sky-800 dark:via-purple-900 dark:to-sky-800
      '>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
};
